- id: databooks
  name: databooks
  description:
    "Remove notebook metadata using `databooks`."
  entry: databooks meta
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types: [jupyter]