[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.poetry]
name = "databooks"
version = "0.1.0"
description = ""
authors = ["Murilo Cunha <murilo@dataroots.io>"]

[tool.poetry.scripts]
databooks = "databooks.cli:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.3.2"
rich = "^10.6.0"
pydantic = "^1.8.2"
GitPython = "^3.1.24"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.2"
flake8 = "^3.9.2"
pytest = "^6.2.4"
pytest-cov = "^3.0.0"
coverage = "^6.2"
typer-cli = "^0.0.12"
lxml = "^4.6.4"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
