name: docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install poetry==1.1.7
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Create coverage report
        run: pytest --cov-report html --cov=databooks tests/
      - name: Deploy docs
        run: mkdocs gh-deploy --force
